ALTER TABLE users
ADD COLUMN IF NOT EXISTS username VARCHAR(100);

ALTER TABLE users
ADD COLUMN IF NOT EXISTS role VARCHAR(50) DEFAULT 'Tester';

ALTER TABLE users
ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'Active';

ALTER TABLE users
ADD COLUMN IF NOT EXISTS auth_token VARCHAR(255);